// Built-in passphrase word list: short, common, lowercase English words.
// Deduplicated at load time; tests check there are at least 2048 unique entries.

const RAW = `
able about above absent accept access acid acorn across act action active actor adapt add address adjust admire admit adopt adult advice afford after again agent agree ahead aim air airport aisle alarm album alert alien alike alive alley allow almost alone along aloud alpha already also alter always amber amount amuse anchor ancient angle animal ankle annual answer antler anvil any apart apple apply april apron arch arctic area arena argue arise arm armor army aroma around arrive arrow art artist ash aside ask asleep aspect assist atlas atom attach attic audio august aunt author auto autumn avenue avoid awake award aware away axis
baby back bacon badge bag bagel bake baker balance ball bamboo banana band bank banner bar barely barn barrel base basic basin basket bat batch bath battle bay beach beacon beak beam bean bear beard beast beat beauty become bed bee beef before begin behave behind being bell belly belt bench bend berry best better beyond bicycle big bike bill bind bird birth biscuit bit bite black blade blank blanket blast blaze blend bless blind blink block blog blond blood bloom blossom blouse blue blunt blush board boat body boil bold bolt bone bonus book boost boot border boring borrow boss both bottle bottom bounce bowl box boy brain brake branch brass brave bread break breeze brick bride bridge brief bright bring brisk broad broken bronze brook broom brother brown brush bubble bucket buddy budget buffalo build bulb bulk bunch bundle bunny burden burger burst bus bush business busy butter button buyer buzz
cabin cable cactus cage cake calm camel camera camp canal candle candy cane canoe canvas canyon cap capable cape captain car carbon card cargo carpet carrot carry cart case cash castle casual cat catalog catch cattle cause cave cedar ceiling celery cell cement census cereal certain chair chalk champion change chapter charge chart chase cheap check cheek cheese chef cherry chest chew chicken chief child chimney chin chip choice choose chorus chunk cider cinema circle citizen city civil claim clap clarify class claw clay clean clerk clever click client cliff climb clinic clip clock close cloth cloud clown club clue cluster coach coast coat cobalt cocoa coconut code coffee coin cold collar colony color column comb combine comet comfort comic common company concert condor cone confirm control cook cookie cool copper copy coral core corn corner correct cost cotton couch count country couple course cousin cover coyote crab crack cradle craft crane crash crater crawl crayon cream credit creek crew cricket crisp critic crop cross crowd crown crucial cruise crumb crunch crush crystal cube cup cupboard curious current curtain curve cushion custom cute cycle
dad daily dairy daisy damp dance danger dare dark dash data date dawn day deal debate decade decide deck declare decor deep deer define degree delay deliver demand denim dense dental deny depart depth deputy derive desert design desk detail detect device devote diagram dial diamond diary diesel diet differ digital dignity dinner dinosaur direct dirt disco dish display distant dive divide doctor dog doll dolphin domain donate donkey donut door dose double dove down dozen draft dragon drama draw dream dress drift drill drink drip drive drop drum dry duck dune during dust dutch duty dwarf dynamic
eager eagle early earn earth easily east easy echo eclipse ecology edge edit effort egg eight either elbow elder elect elegant element elephant elevator elite else embark embrace emerge emotion employ empty enable enact end endless energy enforce engage engine enjoy enlist enough enrich enroll ensure enter entire entry envelope episode equal equip era erase erode escape essay estate eternal even event ever evidence evolve exact example excess exchange excite exclude excuse exhibit exile exist exit exotic expand expect expert explain expose extend extra eye eyebrow
fabric face fact fade faint faith fall false fame family famous fan fancy far farm fashion fast father fault favor feather feature february fee feed feel female fence festival fetch fever few fiber fiction field figure file film filter final find fine finger finish fire firm first fiscal fish fit fitness fix flag flame flash flat flavor flee flight flip float flock floor flower fluid flush fly foam focus fog foil fold follow food foot force forest forget fork fortune forum forward fossil foster found fox fragile frame frequent fresh friend fringe frog front frost frown frozen fruit fuel fun funny furnace future
gadget gain galaxy gallery game gap garage garden garlic garment gas gasp gate gather gauge gaze general genius genre gentle genuine gesture ghost giant gift giggle ginger giraffe girl give glad glance glare glass glide glimpse globe glory glove glow glue goat goal gold good goose gorilla gospel gossip govern gown grab grace grain grant grape grass gravity great green grid grit grocery group grow grunt guard guess guide guitar gym
habit hair half hammer hamster hand happy harbor hard harvest hat have hawk hazard head health heart heavy hedge height hello helmet help hen hero hidden high hill hint hip hire history hobby hockey hold hole holiday hollow home honey hood hope horn horse hospital host hotel hour hover hub huge human humble humor hundred hungry hunt hurdle hurry husband hybrid
ice icon idea identify idle ignore ill image imitate impact impose improve impulse inch include income increase index indicate indoor industry infant inflict inform inhale inherit initial inject injury inner innocent input inquiry insect inside inspire install intact interest into invest invite involve iron island isolate issue item ivory
jacket jaguar jar jazz jealous jeans jelly jewel job join joke journey joy judge juice jump jungle junior junk just
kangaroo keen keep ketchup key kick kid kidney kind kingdom kit kitchen kite kitten kiwi knee knife knock know
lab label labor ladder lady lake lamp language laptop large later latin laugh laundry lava law lawn lawsuit layer lazy leader leaf learn leave lecture left leg legal legend leisure lemon lend length lens leopard lesson letter level liberty library license life lift light like limb limit link lion liquid list little live lizard load loan lobster local lock logic lonely long loop lottery loud lounge love loyal lucky luggage lumber lunar lunch luxury lyrics
machine mad magic magnet maid mail main major make mammal man manage mandate mango mansion manual maple marble march margin marine market marriage mask mass master match material math matrix matter maximum maze meadow mean measure meat mechanic medal media melody melt member memory mention menu mercy merge merit merry mesh message metal method middle midnight milk million mimic mind minimum minor minute miracle mirror miss mistake mix mixed mixture mobile model modify mom moment monitor monkey monster month moon moral more morning mosquito mother motion motor mountain mouse move movie much muffin mule multiply muscle museum mushroom music must mutual myself mystery myth
naive name napkin narrow nation nature near neck need needle negative neglect neither nephew nerve nest net network neutral never news next nice night noble noise nominee noodle normal north nose notable note nothing notice novel now nuclear number nurse nut
oak obey object oblige obscure observe obtain obvious occur ocean october odor off offer office often oil okay old olive olympic omit once one onion online only open opera opinion oppose option orange orbit orchard order ordinary organ orient original orphan ostrich other outdoor outer output outside oval oven over own owner oxygen oyster ozone
pact paddle page pair palace palm panda panel panic panther paper parade parent park parrot party pass patch path patient patrol pattern pause pave payment peace peanut pear peasant pelican pen penalty pencil people pepper perfect permit person pet phone photo phrase physical piano picnic picture piece pig pigeon pill pilot pink pioneer pipe pitch pizza place planet plastic plate play please pledge pluck plug plunge poem poet point polar pole police pond pony pool popular portion position possible post potato pottery poverty powder power practice praise predict prefer prepare present pretty prevent price pride primary print priority prison private prize problem process produce profit program project promote proof property prosper protect proud provide public pudding pull pulp pulse pumpkin punch pupil puppy purchase purity purpose purse push put puzzle pyramid
quality quantum quarter question quick quit quiz quote
rabbit raccoon race rack radar radio rail rain raise rally ramp ranch random range rapid rare rate rather raven raw razor ready real reason rebel rebuild recall receive recipe record recycle reduce reflect reform refuse region regret regular reject relax release relief rely remain remember remind remove render renew rent reopen repair repeat replace report require rescue resemble resist resource response result retire retreat return reunion reveal review reward rhythm rib ribbon rice rich ride ridge right rigid ring ripple risk ritual rival river road roast robot robust rocket romance roof rookie room rose rotate rough round route royal rubber rude rug rule run runway rural
sad saddle sadness safe sail salad salmon salon salt salute same sample sand satisfy sauce sausage save say scale scan scare scatter scene scheme school science scissors scorpion scout scrap screen script scrub sea search season seat second secret section security seed seek segment select sell seminar senior sense sentence series service session settle setup seven shadow shaft shallow share shed shell sheriff shield shift shine ship shiver shock shoe shoot shop short shoulder shove shrimp shrug shuffle shy sibling side siege sight sign silent silk silly silver similar simple since sing siren sister situate six size skate sketch ski skill skin skirt skull slab slam sleep slender slice slide slight slim slogan slot slow slush small smart smile smoke smooth snack snake snap sniff snow soap soccer social sock soda soft solar soldier solid solution solve someone song soon sorry sort soul sound soup source south space spare spatial spawn speak special speed spell spend sphere spice spider spike spin spirit split spoil sponsor spoon sport spot spray spread spring spy square squeeze squirrel stable stadium staff stage stairs stamp stand start state stay steak steel stem step stereo stick still sting stock stomach stone stool story stove strategy street strike strong struggle student stuff stumble style subject submit subway success such sudden suffer sugar suggest suit summer sun sunny sunset super supply supreme sure surface surge surprise surround survey suspect sustain swallow swamp swap swarm swear sweet swift swim swing switch symbol symptom syrup system
table tackle tag tail talent talk tank tape target task taste tattoo taxi teach team tell ten tenant tennis tent term test text thank that theme then theory there they thing this thought three thrive throw thumb thunder ticket tide tiger tilt timber time tiny tip tired tissue title toast today toddler toe together toilet token tomato tomorrow tone tongue tonight tool tooth top topic topple torch tornado tortoise toss total tourist toward tower town toy track trade traffic tragic train transfer trap trash travel tray treat tree trend trial tribe trick trigger trim trip trophy trouble truck true truly trumpet trust truth try tube tuition tumble tuna tunnel turkey turn turtle twelve twenty twice twin twist two type typical
ugly umbrella unable unaware uncle uncover under undo unfair unfold unhappy uniform unique unit universe unknown unlock until unusual unveil update upgrade uphold upon upper upset urban urge usage use used useful useless usual utility
vacant vacuum vague valid valley valve van vanish vapor various vast vault vehicle velvet vendor venture venue verb verify version very vessel veteran viable vibrant victory video view village vintage violin virtual virus visa visit visual vital vivid vocal voice void volcano volume vote voyage
wage wagon wait walk wall walnut want warm warrior wash wasp waste water wave way wealth wear weasel weather web wedding weekend weird welcome west wet whale what wheat wheel when where whip whisper wide width wife wild will win window wine wing wink winner winter wire wisdom wise wish witness wolf woman wonder wood wool word work world worry worth wrap wreck wrestle wrist write wrong
yard year yellow you young youth zebra zero zone zoo
acre adobe agile aloe amber angel apex aqua arbor atoll avid axle bagel balmy banjo basil bayou beige berth bingo birch bison blimp bluff bongo booth bran brine brisk broth buggy bugle bunk cabin cairn camel candy cargo carob cello chard chime chive cider cinch civic clasp cleft cloak clove coral cove crate crest cumin curio dairy delta denim depot diner dingo disco ditto dodge dove dowel duvet easel ebony elfin elm ember emu envoy epoch fable fern ferry fiddle fjord flint flora flute foyer fudge gecko geyser glade gnome gravy grove guava gulf gusto haiku halo hazel heron hiker hippo holly hyena igloo inlet iris jade jolly kayak kebab koala latch lemur lilac linen llama lodge lotus lupin lynx macaw mango maple marsh mauve medal melon mint mocha moose moss motel mulch nacho nectar nimbus nomad nutmeg oasis ocelot olive omega opal orca otter oxbow paddy pagoda pansy papaya parka pasta peach pecan penny perch pesto petal piano plaza plum polka poppy prism puffin quail quartz quilt radish rainy relic robin rodeo rumba rustic saga salsa sapphire satin scarf scone sepia sequin sherpa silo sloth snowy sonar spruce squid stork sunny swan tabby taco talon tango tapir tartan teal tempo thyme tofu topaz totem tulip tundra turnip tuxedo umber vanilla velcro viper vista waffle walrus wasabi willow wombat yacht yak yodel yogurt yonder zesty zinc zinnia
acorn actual adept aerial affix agenda alumni amble ample annex anthem apron ardent aspen astute attire avert awning bakery balcony ballad baton beaker bellow beret bistro blazer bleach blotch bobcat bonnet bootie bouquet boxer braid breezy bridle bristle brunch buckle bumpy burrow butane cabana cadet caramel cashew catnip caviar chalet chapel cheery chorus cinder citrus clamor clever cobweb comedy convoy cosmic cotton cougar crafty crimson crouton crumble cuckoo cumulus curly cutlass dapper dazzle debut decoy deluxe dimple docile doodle dozing drowsy dugout eclair effect elated emerald encore endive exotic fabled falcon fedora fennel fescue fiesta finch flannel flutter fondue fossil freckle frolic gallop garnet gazebo gelato gerbil giddy ginkgo glossy goblet gopher gourd granite gravel griddle grotto gumbo gusty hamlet harp hatchet haven herald hermit hickory hiccup hubcap hummus humid hustle iceberg impish indigo inkwell jackal jargon jasmine javelin jester jigsaw jockey jovial jubilee juniper karate kennel kernel kettle kindle kipper knack kumquat lagoon lantern lapel larch lasso lattice lavender ledger lentil lettuce lichen limber lobby locket lucid lullaby lumen magenta mallard mantle marlin mascot meadow mellow meteor mingle minnow mitten modest mohair molten monarch mosaic muesli muffin mural muster nebula nickel nimble noodle nougat nozzle oatmeal obelisk octave omelet onward orchid oriole outfit paddle palette pantry parsley pastel patio pebble pepper piccolo pickle pillow pinwheel pistachio plaid plume pocket polish pollen poncho porch pretzel prairie primal pueblo pulley quaint quiver raffle rainbow ramble raisin rattle recital reindeer riddle rocky rubble ruby rustle saffron salami sandal sapling scallop scooter sesame shanty sherbet shovel sizzle skillet skipper slipper sorbet sparrow spindle sprout starch stencil stubby summit sundial swivel tadpole tamale tassel teapot thimble thistle timid tinsel toffee trellis trivia trolley trowel truffle tumbler turban tweed upbeat valiant velour verdant vinyl violet walnut wander warble whisk whistle wicker widget wigwam wizard woolly wrangle yarrow yearly zephyr zigzag zipper
`;

/** Unique, lowercase, a–z only. */
export const WORDS: readonly string[] = [...new Set(RAW.split(/\s+/).filter((w) => /^[a-z]{3,9}$/.test(w)))];
