// Generates the lightweight Learn catalog and search index from src/learn/content.
// Pages list and link content from the catalog, and only load a subject, problem file
// or case study when it's opened, so the full ~3 MB of lessons never ships up front.
//
//   npx tsx scripts/generate-learn-catalog.ts          write the files
//   npx tsx scripts/generate-learn-catalog.ts --check  exit 1 if they're out of date

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { subjects } from '../src/learn/content/index.ts';
import { caseStudies } from '../src/learn/content/case-studies/index.ts';
import type { Problem } from '../src/learn/types/problem.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src/learn/data');
const problemsDir = join(root, 'src/learn/content/problems');

async function problemFiles() {
  const files = readdirSync(problemsDir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts' && f !== 'categories.ts')
    .sort();
  const result: { file: string; problems: Problem[] }[] = [];
  for (const f of files) {
    const mod = (await import(join(problemsDir, f))) as Record<string, unknown>;
    const list = Object.values(mod).find(Array.isArray) as Problem[] | undefined;
    if (!list) throw new Error(`No problem array exported from ${f}`);
    result.push({ file: basename(f, '.ts'), problems: list });
  }
  return result;
}

async function caseStudyFiles() {
  const dir = join(root, 'src/learn/content/case-studies');
  const byId = new Map<string, string>();
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.ts') && f !== 'index.ts')) {
    const mod = (await import(join(dir, f))) as Record<string, { id?: string }>;
    for (const v of Object.values(mod)) if (v && typeof v.id === 'string') byId.set(v.id, basename(f, '.ts'));
  }
  return byId;
}

const clean = (s: string) => s.replace(/[*`]/g, '').replace(/\s+/g, ' ').trim();

async function main() {
  const files = await problemFiles();
  const caseFiles = await caseStudyFiles();
  const catalog = {
    subjects: subjects.map((s) => ({
      id: s.id,
      title: s.title,
      description: s.description,
      topics: s.topics.map((t) => ({
        id: t.id,
        title: t.title,
        level: t.level,
        description: t.description,
        prerequisites: t.prerequisites ?? [],
        relatedTopics: t.relatedTopics,
      })),
    })),
    problems: files.flatMap(({ file, problems }) =>
      problems.map((p) => ({ id: p.id, title: p.title, difficulty: p.difficulty, category: p.category, file })),
    ),
    caseStudies: caseStudies.map((c) => ({
      id: c.id,
      title: c.title,
      difficulty: c.difficulty,
      summary: c.summary,
      relatedTopics: c.relatedTopics ?? [],
      file: caseFiles.get(c.id)!,
    })),
  };

  const search = [
    ...subjects.flatMap((s) =>
      s.topics.map((t) => ({
        kind: 'topic' as const,
        subjectId: s.id,
        id: t.id,
        title: t.title,
        description: t.description,
        text: clean([t.title, t.description, ...(t.keywords ?? []), t.explanation].join(' ')).toLowerCase(),
      })),
    ),
    ...files.flatMap(({ problems }) =>
      problems.map((p) => ({
        kind: 'problem' as const,
        subjectId: p.category,
        id: p.id,
        title: p.title,
        description: `${p.difficulty} · ${clean(p.description).slice(0, 140)}`,
        text: clean([p.title, p.difficulty, p.category, ...(p.keywords ?? []), p.description].join(' ')).toLowerCase(),
      })),
    ),
    ...caseStudies.map((c) => ({
      kind: 'case-study' as const,
      subjectId: 'case-studies',
      id: c.id,
      title: c.title,
      description: c.summary,
      text: clean([c.title, c.summary, ...(c.keywords ?? []), c.problemStatement].join(' ')).toLowerCase(),
    })),
  ];

  const header = '// Generated by scripts/generate-learn-catalog.ts. Do not edit by hand.\n';
  const outputs: [string, string][] = [
    [
      'catalog.generated.ts',
      `${header}import type { LearnCatalog } from './catalog.types';\n\nexport const catalog: LearnCatalog = ${JSON.stringify(catalog, null, 2)};\n`,
    ],
    [
      'search.generated.ts',
      `${header}import type { SearchEntry } from './catalog.types';\n\nexport const searchEntries: SearchEntry[] = ${JSON.stringify(search)};\n`,
    ],
    [
      // Tiny counts for the main site's home page, so it needn't load the catalog.
      'stats.generated.ts',
      `${header}export const learnStats = ${JSON.stringify({
        subjects: catalog.subjects.length,
        topics: catalog.subjects.reduce((n, s) => n + s.topics.length, 0),
        problems: catalog.problems.length,
        caseStudies: catalog.caseStudies.length,
      })};\n`,
    ],
  ];

  const check = process.argv.includes('--check');
  let stale = false;
  for (const [name, text] of outputs) {
    const path = join(out, name);
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // missing counts as stale
    }
    if (current === text) continue;
    stale = true;
    if (!check) writeFileSync(path, text);
    console.log(`${check ? 'Out of date' : 'Wrote'}: src/learn/data/${name} (${(text.length / 1024).toFixed(0)} KB)`);
  }
  if (check && stale) {
    console.error('Run `npm run generate:learn` and commit the result.');
    process.exit(1);
  }
}

await main();
