// Rewrites the tool list in README.md (between the TOOLS markers) from src/tools/registry.ts,
// so the README never drifts from what the site actually ships.
//
//   npm run generate:readme          update README.md
//   npm run generate:readme -- --check   exit 1 if it's out of date

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  status: string;
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// Imported by path at run time (like scripts/seo-plugin.ts) so the Node typecheck doesn't follow it into React pages.
const { TOOLS } = (await import(pathToFileURL(join(root, 'src/tools/registry.ts')).href)) as { TOOLS: Tool[] };
const toolPath = (t: Tool) => `/tools/${t.id}`;
const readme = join(root, 'README.md');
const START = '<!-- TOOLS:START (generated by `npm run generate:readme`; edit src/tools/*/index.ts instead) -->';
const END = '<!-- TOOLS:END -->';

const tools = TOOLS.filter((t) => t.status !== 'coming-soon');
const categories = [...new Set(tools.map((t) => t.category))];
const cell = (s: string) => s.replace(/\|/g, '\\|');

const block = [
  START,
  '',
  `${tools.length} tools in ${categories.length} categories.`,
  '',
  ...categories.flatMap((cat) => {
    const list = tools.filter((t) => t.category === cat);
    return [
      `### ${cat} (${list.length})`,
      '',
      '| Tool | What it does |',
      '|---|---|',
      ...list.map((t) => `| [**${cell(t.name)}**](https://zykit.vercel.app${toolPath(t)}) | ${cell(t.description)} |`),
      '',
    ];
  }),
  END,
].join('\n');

const current = readFileSync(readme, 'utf8');
const start = current.indexOf(START.slice(0, 16));
const end = current.indexOf(END);
if (start === -1 || end === -1) throw new Error('README.md is missing the TOOLS:START / TOOLS:END markers');
const next = current.slice(0, start) + block + current.slice(end + END.length);

if (process.argv.includes('--check')) {
  if (next !== current) {
    console.error('README tool list is out of date. Run `npm run generate:readme`.');
    process.exit(1);
  }
} else if (next !== current) {
  writeFileSync(readme, next);
  console.log(`README.md: listed ${tools.length} tools`);
}
