// A compact Unicode character name table for the most common blocks. Names for accented Latin
// letters are derived from their canonical decomposition (base letter + one combining mark);
// CJK ideographs, Hangul syllables, variation selectors, tags and regional indicators are
// algorithmic. Anything else falls back to its block and general category in the UI.

/** Sequential names from a start code point ('' = no name listed). */
function seq(start: number, names: string, prefix = ''): [number, string][] {
  return names.split('|').flatMap((n, i) => (n ? [[start + i, prefix + n] as [number, string]] : []));
}

const C0 =
  'NULL|START OF HEADING|START OF TEXT|END OF TEXT|END OF TRANSMISSION|ENQUIRY|ACKNOWLEDGE|BELL|BACKSPACE|CHARACTER TABULATION|LINE FEED (LF)|LINE TABULATION|FORM FEED (FF)|CARRIAGE RETURN (CR)|SHIFT OUT|SHIFT IN|DATA LINK ESCAPE|DEVICE CONTROL ONE|DEVICE CONTROL TWO|DEVICE CONTROL THREE|DEVICE CONTROL FOUR|NEGATIVE ACKNOWLEDGE|SYNCHRONOUS IDLE|END OF TRANSMISSION BLOCK|CANCEL|END OF MEDIUM|SUBSTITUTE|ESCAPE|INFORMATION SEPARATOR FOUR|INFORMATION SEPARATOR THREE|INFORMATION SEPARATOR TWO|INFORMATION SEPARATOR ONE';

const ASCII_PUNCT =
  'SPACE|EXCLAMATION MARK|QUOTATION MARK|NUMBER SIGN|DOLLAR SIGN|PERCENT SIGN|AMPERSAND|APOSTROPHE|LEFT PARENTHESIS|RIGHT PARENTHESIS|ASTERISK|PLUS SIGN|COMMA|HYPHEN-MINUS|FULL STOP|SOLIDUS|DIGIT ZERO|DIGIT ONE|DIGIT TWO|DIGIT THREE|DIGIT FOUR|DIGIT FIVE|DIGIT SIX|DIGIT SEVEN|DIGIT EIGHT|DIGIT NINE|COLON|SEMICOLON|LESS-THAN SIGN|EQUALS SIGN|GREATER-THAN SIGN|QUESTION MARK|COMMERCIAL AT';

const LATIN1 =
  'NO-BREAK SPACE|INVERTED EXCLAMATION MARK|CENT SIGN|POUND SIGN|CURRENCY SIGN|YEN SIGN|BROKEN BAR|SECTION SIGN|DIAERESIS|COPYRIGHT SIGN|FEMININE ORDINAL INDICATOR|LEFT-POINTING DOUBLE ANGLE QUOTATION MARK|NOT SIGN|SOFT HYPHEN|REGISTERED SIGN|MACRON|DEGREE SIGN|PLUS-MINUS SIGN|SUPERSCRIPT TWO|SUPERSCRIPT THREE|ACUTE ACCENT|MICRO SIGN|PILCROW SIGN|MIDDLE DOT|CEDILLA|SUPERSCRIPT ONE|MASCULINE ORDINAL INDICATOR|RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK|VULGAR FRACTION ONE QUARTER|VULGAR FRACTION ONE HALF|VULGAR FRACTION THREE QUARTERS|INVERTED QUESTION MARK';

const GENERAL_PUNCTUATION =
  'EN QUAD|EM QUAD|EN SPACE|EM SPACE|THREE-PER-EM SPACE|FOUR-PER-EM SPACE|SIX-PER-EM SPACE|FIGURE SPACE|PUNCTUATION SPACE|THIN SPACE|HAIR SPACE|ZERO WIDTH SPACE|ZERO WIDTH NON-JOINER|ZERO WIDTH JOINER|LEFT-TO-RIGHT MARK|RIGHT-TO-LEFT MARK|' +
  'HYPHEN|NON-BREAKING HYPHEN|FIGURE DASH|EN DASH|EM DASH|HORIZONTAL BAR|DOUBLE VERTICAL LINE|DOUBLE LOW LINE|LEFT SINGLE QUOTATION MARK|RIGHT SINGLE QUOTATION MARK|SINGLE LOW-9 QUOTATION MARK|SINGLE HIGH-REVERSED-9 QUOTATION MARK|LEFT DOUBLE QUOTATION MARK|RIGHT DOUBLE QUOTATION MARK|DOUBLE LOW-9 QUOTATION MARK|DOUBLE HIGH-REVERSED-9 QUOTATION MARK|' +
  'DAGGER|DOUBLE DAGGER|BULLET|TRIANGULAR BULLET|ONE DOT LEADER|TWO DOT LEADER|HORIZONTAL ELLIPSIS|HYPHENATION POINT|LINE SEPARATOR|PARAGRAPH SEPARATOR|LEFT-TO-RIGHT EMBEDDING|RIGHT-TO-LEFT EMBEDDING|POP DIRECTIONAL FORMATTING|LEFT-TO-RIGHT OVERRIDE|RIGHT-TO-LEFT OVERRIDE|NARROW NO-BREAK SPACE|' +
  'PER MILLE SIGN|PER TEN THOUSAND SIGN|PRIME|DOUBLE PRIME|TRIPLE PRIME|REVERSED PRIME|REVERSED DOUBLE PRIME|REVERSED TRIPLE PRIME|CARET|SINGLE LEFT-POINTING ANGLE QUOTATION MARK|SINGLE RIGHT-POINTING ANGLE QUOTATION MARK|REFERENCE MARK|DOUBLE EXCLAMATION MARK|INTERROBANG|OVERLINE|UNDERTIE|' +
  'CHARACTER TIE|CARET INSERTION POINT|ASTERISM|HYPHEN BULLET|FRACTION SLASH|LEFT SQUARE BRACKET WITH QUILL|RIGHT SQUARE BRACKET WITH QUILL|DOUBLE QUESTION MARK|QUESTION EXCLAMATION MARK|EXCLAMATION QUESTION MARK|TIRONIAN SIGN ET|REVERSED PILCROW SIGN|BLACK LEFTWARDS BULLET|BLACK RIGHTWARDS BULLET|LOW ASTERISK|REVERSED SEMICOLON|' +
  'CLOSE UP|TWO ASTERISKS ALIGNED VERTICALLY|COMMERCIAL MINUS SIGN|SWUNG DASH|INVERTED UNDERTIE|FLOWER PUNCTUATION MARK|THREE DOT PUNCTUATION|QUADRUPLE PRIME|FOUR DOT PUNCTUATION|FIVE DOT PUNCTUATION|TWO DOT PUNCTUATION|FOUR DOT MARK|DOTTED CROSS|TRICOLON|VERTICAL FOUR DOTS|MEDIUM MATHEMATICAL SPACE|' +
  'WORD JOINER|FUNCTION APPLICATION|INVISIBLE TIMES|INVISIBLE SEPARATOR|INVISIBLE PLUS||LEFT-TO-RIGHT ISOLATE|RIGHT-TO-LEFT ISOLATE|FIRST STRONG ISOLATE|POP DIRECTIONAL ISOLATE|INHIBIT SYMMETRIC SWAPPING|ACTIVATE SYMMETRIC SWAPPING|INHIBIT ARABIC FORM SHAPING|ACTIVATE ARABIC FORM SHAPING|NATIONAL DIGIT SHAPES|NOMINAL DIGIT SHAPES';

const CURRENCY =
  'EURO-CURRENCY SIGN|COLON SIGN|CRUZEIRO SIGN|FRENCH FRANC SIGN|LIRA SIGN|MILL SIGN|NAIRA SIGN|PESETA SIGN|RUPEE SIGN|WON SIGN|NEW SHEQEL SIGN|DONG SIGN|EURO SIGN|KIP SIGN|TUGRIK SIGN|DRACHMA SIGN|GERMAN PENNY SIGN|PESO SIGN|GUARANI SIGN|AUSTRAL SIGN|HRYVNIA SIGN|CEDI SIGN|LIVRE TOURNOIS SIGN|SPESMILO SIGN|TENGE SIGN|INDIAN RUPEE SIGN|TURKISH LIRA SIGN|NORDIC MARK SIGN|MANAT SIGN|RUBLE SIGN|LARI SIGN|BITCOIN SIGN|SOM SIGN';

const ARROWS =
  'LEFTWARDS ARROW|UPWARDS ARROW|RIGHTWARDS ARROW|DOWNWARDS ARROW|LEFT RIGHT ARROW|UP DOWN ARROW|NORTH WEST ARROW|NORTH EAST ARROW|SOUTH EAST ARROW|SOUTH WEST ARROW|LEFTWARDS ARROW WITH STROKE|RIGHTWARDS ARROW WITH STROKE|LEFTWARDS WAVE ARROW|RIGHTWARDS WAVE ARROW|LEFTWARDS TWO HEADED ARROW|UPWARDS TWO HEADED ARROW|' +
  'RIGHTWARDS TWO HEADED ARROW|DOWNWARDS TWO HEADED ARROW|LEFTWARDS ARROW WITH TAIL|RIGHTWARDS ARROW WITH TAIL|LEFTWARDS ARROW FROM BAR|UPWARDS ARROW FROM BAR|RIGHTWARDS ARROW FROM BAR|DOWNWARDS ARROW FROM BAR|UP DOWN ARROW WITH BASE|LEFTWARDS ARROW WITH HOOK|RIGHTWARDS ARROW WITH HOOK';

const MATH =
  'FOR ALL|COMPLEMENT|PARTIAL DIFFERENTIAL|THERE EXISTS|THERE DOES NOT EXIST|EMPTY SET|INCREMENT|NABLA|ELEMENT OF|NOT AN ELEMENT OF|SMALL ELEMENT OF|CONTAINS AS MEMBER|DOES NOT CONTAIN AS MEMBER|SMALL CONTAINS AS MEMBER|END OF PROOF|N-ARY PRODUCT|' +
  'N-ARY COPRODUCT|N-ARY SUMMATION|MINUS SIGN|MINUS-OR-PLUS SIGN|DOT PLUS|DIVISION SLASH|SET MINUS|ASTERISK OPERATOR|RING OPERATOR|BULLET OPERATOR|SQUARE ROOT|CUBE ROOT|FOURTH ROOT|PROPORTIONAL TO|INFINITY|RIGHT ANGLE|' +
  'ANGLE|MEASURED ANGLE|SPHERICAL ANGLE|DIVIDES|DOES NOT DIVIDE|PARALLEL TO|NOT PARALLEL TO|LOGICAL AND|LOGICAL OR|INTERSECTION|UNION|INTEGRAL|DOUBLE INTEGRAL|TRIPLE INTEGRAL|CONTOUR INTEGRAL|SURFACE INTEGRAL|' +
  'VOLUME INTEGRAL|CLOCKWISE INTEGRAL|CLOCKWISE CONTOUR INTEGRAL|ANTICLOCKWISE CONTOUR INTEGRAL|THEREFORE|BECAUSE|RATIO|PROPORTION|DOT MINUS|EXCESS|GEOMETRIC PROPORTION|HOMOTHETIC|TILDE OPERATOR|REVERSED TILDE|INVERTED LAZY S|SINE WAVE|' +
  'WREATH PRODUCT|NOT TILDE|MINUS TILDE|ASYMPTOTICALLY EQUAL TO|NOT ASYMPTOTICALLY EQUAL TO|APPROXIMATELY EQUAL TO|APPROXIMATELY BUT NOT ACTUALLY EQUAL TO|NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO|ALMOST EQUAL TO|NOT ALMOST EQUAL TO';

const BOX_DRAWING =
  'LIGHT HORIZONTAL|HEAVY HORIZONTAL|LIGHT VERTICAL|HEAVY VERTICAL|LIGHT TRIPLE DASH HORIZONTAL|HEAVY TRIPLE DASH HORIZONTAL|LIGHT TRIPLE DASH VERTICAL|HEAVY TRIPLE DASH VERTICAL|LIGHT QUADRUPLE DASH HORIZONTAL|HEAVY QUADRUPLE DASH HORIZONTAL|LIGHT QUADRUPLE DASH VERTICAL|HEAVY QUADRUPLE DASH VERTICAL|LIGHT DOWN AND RIGHT';

const BOX_DOUBLE =
  'DOUBLE HORIZONTAL|DOUBLE VERTICAL|DOWN SINGLE AND RIGHT DOUBLE|DOWN DOUBLE AND RIGHT SINGLE|DOUBLE DOWN AND RIGHT|DOWN SINGLE AND LEFT DOUBLE|DOWN DOUBLE AND LEFT SINGLE|DOUBLE DOWN AND LEFT|UP SINGLE AND RIGHT DOUBLE|UP DOUBLE AND RIGHT SINGLE|DOUBLE UP AND RIGHT|UP SINGLE AND LEFT DOUBLE|UP DOUBLE AND LEFT SINGLE|DOUBLE UP AND LEFT|' +
  'VERTICAL SINGLE AND RIGHT DOUBLE|VERTICAL DOUBLE AND RIGHT SINGLE|DOUBLE VERTICAL AND RIGHT|VERTICAL SINGLE AND LEFT DOUBLE|VERTICAL DOUBLE AND LEFT SINGLE|DOUBLE VERTICAL AND LEFT|DOWN SINGLE AND HORIZONTAL DOUBLE|DOWN DOUBLE AND HORIZONTAL SINGLE|DOUBLE DOWN AND HORIZONTAL|UP SINGLE AND HORIZONTAL DOUBLE|UP DOUBLE AND HORIZONTAL SINGLE|DOUBLE UP AND HORIZONTAL|' +
  'VERTICAL SINGLE AND HORIZONTAL DOUBLE|VERTICAL DOUBLE AND HORIZONTAL SINGLE|DOUBLE VERTICAL AND HORIZONTAL|LIGHT ARC DOWN AND RIGHT|LIGHT ARC DOWN AND LEFT|LIGHT ARC UP AND LEFT|LIGHT ARC UP AND RIGHT|LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT|LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT|LIGHT DIAGONAL CROSS';

const GREEK_LETTERS = 'ALPHA|BETA|GAMMA|DELTA|EPSILON|ZETA|ETA|THETA|IOTA|KAPPA|LAMDA|MU|NU|XI|OMICRON|PI|RHO|FINAL SIGMA|SIGMA|TAU|UPSILON|PHI|CHI|PSI|OMEGA';
const CYRILLIC_BASIC = 'A|BE|VE|GHE|DE|IE|ZHE|ZE|I|SHORT I|KA|EL|EM|EN|O|PE|ER|ES|TE|U|EF|HA|TSE|CHE|SHA|SHCHA|HARD SIGN|YERU|SOFT SIGN|E|YU|YA';
const CYRILLIC_EXTRA = 'IE WITH GRAVE|IO|DJE|GJE|UKRAINIAN IE|DZE|BYELORUSSIAN-UKRAINIAN I|YI|JE|LJE|NJE|TSHE|KJE|I WITH GRAVE|SHORT U|DZHE';

const SINGLES: [number, string][] = [
  [0x7f, 'DELETE'],
  [0x85, 'NEXT LINE (NEL)'],
  [0x5b, 'LEFT SQUARE BRACKET'],
  [0x5c, 'REVERSE SOLIDUS'],
  [0x5d, 'RIGHT SQUARE BRACKET'],
  [0x5e, 'CIRCUMFLEX ACCENT'],
  [0x5f, 'LOW LINE'],
  [0x60, 'GRAVE ACCENT'],
  [0x7b, 'LEFT CURLY BRACKET'],
  [0x7c, 'VERTICAL LINE'],
  [0x7d, 'RIGHT CURLY BRACKET'],
  [0x7e, 'TILDE'],
  [0xc6, 'LATIN CAPITAL LETTER AE'],
  [0xd0, 'LATIN CAPITAL LETTER ETH'],
  [0xd7, 'MULTIPLICATION SIGN'],
  [0xd8, 'LATIN CAPITAL LETTER O WITH STROKE'],
  [0xde, 'LATIN CAPITAL LETTER THORN'],
  [0xdf, 'LATIN SMALL LETTER SHARP S'],
  [0xe6, 'LATIN SMALL LETTER AE'],
  [0xf0, 'LATIN SMALL LETTER ETH'],
  [0xf7, 'DIVISION SIGN'],
  [0xf8, 'LATIN SMALL LETTER O WITH STROKE'],
  [0xfe, 'LATIN SMALL LETTER THORN'],
  [0x110, 'LATIN CAPITAL LETTER D WITH STROKE'],
  [0x111, 'LATIN SMALL LETTER D WITH STROKE'],
  [0x126, 'LATIN CAPITAL LETTER H WITH STROKE'],
  [0x127, 'LATIN SMALL LETTER H WITH STROKE'],
  [0x131, 'LATIN SMALL LETTER DOTLESS I'],
  [0x132, 'LATIN CAPITAL LIGATURE IJ'],
  [0x133, 'LATIN SMALL LIGATURE IJ'],
  [0x138, 'LATIN SMALL LETTER KRA'],
  [0x13f, 'LATIN CAPITAL LETTER L WITH MIDDLE DOT'],
  [0x140, 'LATIN SMALL LETTER L WITH MIDDLE DOT'],
  [0x141, 'LATIN CAPITAL LETTER L WITH STROKE'],
  [0x142, 'LATIN SMALL LETTER L WITH STROKE'],
  [0x149, 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE'],
  [0x14a, 'LATIN CAPITAL LETTER ENG'],
  [0x14b, 'LATIN SMALL LETTER ENG'],
  [0x152, 'LATIN CAPITAL LIGATURE OE'],
  [0x153, 'LATIN SMALL LIGATURE OE'],
  [0x166, 'LATIN CAPITAL LETTER T WITH STROKE'],
  [0x167, 'LATIN SMALL LETTER T WITH STROKE'],
  [0x17f, 'LATIN SMALL LETTER LONG S'],
  [0x180, 'LATIN SMALL LETTER B WITH STROKE'],
  [0x181, 'LATIN CAPITAL LETTER B WITH HOOK'],
  [0x186, 'LATIN CAPITAL LETTER OPEN O'],
  [0x189, 'LATIN CAPITAL LETTER AFRICAN D'],
  [0x18e, 'LATIN CAPITAL LETTER REVERSED E'],
  [0x18f, 'LATIN CAPITAL LETTER SCHWA'],
  [0x190, 'LATIN CAPITAL LETTER OPEN E'],
  [0x191, 'LATIN CAPITAL LETTER F WITH HOOK'],
  [0x192, 'LATIN SMALL LETTER F WITH HOOK'],
  [0x194, 'LATIN CAPITAL LETTER GAMMA'],
  [0x196, 'LATIN CAPITAL LETTER IOTA'],
  [0x197, 'LATIN CAPITAL LETTER I WITH STROKE'],
  [0x19b, 'LATIN SMALL LETTER LAMBDA WITH STROKE'],
  [0x19d, 'LATIN CAPITAL LETTER N WITH LEFT HOOK'],
  [0x19f, 'LATIN CAPITAL LETTER O WITH MIDDLE TILDE'],
  [0x1a9, 'LATIN CAPITAL LETTER ESH'],
  [0x1b1, 'LATIN CAPITAL LETTER UPSILON'],
  [0x1b2, 'LATIN CAPITAL LETTER V WITH HOOK'],
  [0x1b5, 'LATIN CAPITAL LETTER Z WITH STROKE'],
  [0x1b6, 'LATIN SMALL LETTER Z WITH STROKE'],
  [0x1b7, 'LATIN CAPITAL LETTER EZH'],
  [0x1c0, 'LATIN LETTER DENTAL CLICK'],
  [0x1c1, 'LATIN LETTER LATERAL CLICK'],
  [0x1c2, 'LATIN LETTER ALVEOLAR CLICK'],
  [0x1c3, 'LATIN LETTER RETROFLEX CLICK'],
  [0x1c4, 'LATIN CAPITAL LETTER DZ WITH CARON'],
  [0x1c5, 'LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON'],
  [0x1c6, 'LATIN SMALL LETTER DZ WITH CARON'],
  [0x1c7, 'LATIN CAPITAL LETTER LJ'],
  [0x1c8, 'LATIN CAPITAL LETTER L WITH SMALL LETTER J'],
  [0x1c9, 'LATIN SMALL LETTER LJ'],
  [0x1ca, 'LATIN CAPITAL LETTER NJ'],
  [0x1cb, 'LATIN CAPITAL LETTER N WITH SMALL LETTER J'],
  [0x1cc, 'LATIN SMALL LETTER NJ'],
  [0x1dd, 'LATIN SMALL LETTER TURNED E'],
  [0x1e4, 'LATIN CAPITAL LETTER G WITH STROKE'],
  [0x1e5, 'LATIN SMALL LETTER G WITH STROKE'],
  [0x1f1, 'LATIN CAPITAL LETTER DZ'],
  [0x1f2, 'LATIN CAPITAL LETTER D WITH SMALL LETTER Z'],
  [0x1f3, 'LATIN SMALL LETTER DZ'],
  [0x237, 'LATIN SMALL LETTER DOTLESS J'],
  [0x251, 'LATIN SMALL LETTER ALPHA'],
  [0x259, 'LATIN SMALL LETTER SCHWA'],
  [0x261, 'LATIN SMALL LETTER SCRIPT G'],
  [0x26a, 'LATIN LETTER SMALL CAPITAL I'],
  [0x2b9, 'MODIFIER LETTER PRIME'],
  [0x2bb, 'MODIFIER LETTER TURNED COMMA'],
  [0x2bc, 'MODIFIER LETTER APOSTROPHE'],
  [0x2c6, 'MODIFIER LETTER CIRCUMFLEX ACCENT'],
  [0x2c7, 'CARON'],
  [0x2d8, 'BREVE'],
  [0x2d9, 'DOT ABOVE'],
  [0x2da, 'RING ABOVE'],
  [0x2db, 'OGONEK'],
  [0x2dc, 'SMALL TILDE'],
  [0x2dd, 'DOUBLE ACUTE ACCENT'],
  [0x34f, 'COMBINING GRAPHEME JOINER'],
  [0x37e, 'GREEK QUESTION MARK'],
  [0x501, 'CYRILLIC SMALL LETTER KOMI DE'],
  [0x4cf, 'CYRILLIC SMALL LETTER PALOCHKA'],
  [0x61c, 'ARABIC LETTER MARK'],
  [0x115f, 'HANGUL CHOSEONG FILLER'],
  [0x1160, 'HANGUL JUNGSEONG FILLER'],
  [0x1680, 'OGHAM SPACE MARK'],
  [0x180e, 'MONGOLIAN VOWEL SEPARATOR'],
  [0x20e3, 'COMBINING ENCLOSING KEYCAP'],
  [0x2103, 'DEGREE CELSIUS'],
  [0x2109, 'DEGREE FAHRENHEIT'],
  [0x2113, 'SCRIPT SMALL L'],
  [0x2116, 'NUMERO SIGN'],
  [0x2122, 'TRADE MARK SIGN'],
  [0x2126, 'OHM SIGN'],
  [0x212a, 'KELVIN SIGN'],
  [0x212b, 'ANGSTROM SIGN'],
  [0x21b5, 'DOWNWARDS ARROW WITH CORNER LEFTWARDS'],
  [0x21ba, 'ANTICLOCKWISE OPEN CIRCLE ARROW'],
  [0x21bb, 'CLOCKWISE OPEN CIRCLE ARROW'],
  [0x21c4, 'RIGHTWARDS ARROW OVER LEFTWARDS ARROW'],
  [0x21c6, 'LEFTWARDS ARROW OVER RIGHTWARDS ARROW'],
  [0x21d0, 'LEFTWARDS DOUBLE ARROW'],
  [0x21d1, 'UPWARDS DOUBLE ARROW'],
  [0x21d2, 'RIGHTWARDS DOUBLE ARROW'],
  [0x21d3, 'DOWNWARDS DOUBLE ARROW'],
  [0x21d4, 'LEFT RIGHT DOUBLE ARROW'],
  [0x21d5, 'UP DOWN DOUBLE ARROW'],
  [0x21e6, 'LEFTWARDS WHITE ARROW'],
  [0x21e7, 'UPWARDS WHITE ARROW'],
  [0x21e8, 'RIGHTWARDS WHITE ARROW'],
  [0x21e9, 'DOWNWARDS WHITE ARROW'],
  [0x2260, 'NOT EQUAL TO'],
  [0x2261, 'IDENTICAL TO'],
  [0x2262, 'NOT IDENTICAL TO'],
  [0x2263, 'STRICTLY EQUIVALENT TO'],
  [0x2264, 'LESS-THAN OR EQUAL TO'],
  [0x2265, 'GREATER-THAN OR EQUAL TO'],
  [0x2266, 'LESS-THAN OVER EQUAL TO'],
  [0x2267, 'GREATER-THAN OVER EQUAL TO'],
  [0x226a, 'MUCH LESS-THAN'],
  [0x226b, 'MUCH GREATER-THAN'],
  [0x2282, 'SUBSET OF'],
  [0x2283, 'SUPERSET OF'],
  [0x2284, 'NOT A SUBSET OF'],
  [0x2285, 'NOT A SUPERSET OF'],
  [0x2286, 'SUBSET OF OR EQUAL TO'],
  [0x2287, 'SUPERSET OF OR EQUAL TO'],
  [0x2295, 'CIRCLED PLUS'],
  [0x2296, 'CIRCLED MINUS'],
  [0x2297, 'CIRCLED TIMES'],
  [0x2298, 'CIRCLED DIVISION SLASH'],
  [0x2299, 'CIRCLED DOT OPERATOR'],
  [0x22a2, 'RIGHT TACK'],
  [0x22a3, 'LEFT TACK'],
  [0x22a4, 'DOWN TACK'],
  [0x22a5, 'UP TACK'],
  [0x22c0, 'N-ARY LOGICAL AND'],
  [0x22c1, 'N-ARY LOGICAL OR'],
  [0x22c2, 'N-ARY INTERSECTION'],
  [0x22c3, 'N-ARY UNION'],
  [0x22c4, 'DIAMOND OPERATOR'],
  [0x22c5, 'DOT OPERATOR'],
  [0x22c6, 'STAR OPERATOR'],
  [0x22ee, 'VERTICAL ELLIPSIS'],
  [0x22ef, 'MIDLINE HORIZONTAL ELLIPSIS'],
  [0x2510, 'BOX DRAWINGS LIGHT DOWN AND LEFT'],
  [0x2514, 'BOX DRAWINGS LIGHT UP AND RIGHT'],
  [0x2518, 'BOX DRAWINGS LIGHT UP AND LEFT'],
  [0x251c, 'BOX DRAWINGS LIGHT VERTICAL AND RIGHT'],
  [0x2524, 'BOX DRAWINGS LIGHT VERTICAL AND LEFT'],
  [0x252c, 'BOX DRAWINGS LIGHT DOWN AND HORIZONTAL'],
  [0x2534, 'BOX DRAWINGS LIGHT UP AND HORIZONTAL'],
  [0x253c, 'BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL'],
  [0x250f, 'BOX DRAWINGS HEAVY DOWN AND RIGHT'],
  [0x2513, 'BOX DRAWINGS HEAVY DOWN AND LEFT'],
  [0x2517, 'BOX DRAWINGS HEAVY UP AND RIGHT'],
  [0x251b, 'BOX DRAWINGS HEAVY UP AND LEFT'],
  [0x2523, 'BOX DRAWINGS HEAVY VERTICAL AND RIGHT'],
  [0x252b, 'BOX DRAWINGS HEAVY VERTICAL AND LEFT'],
  [0x2533, 'BOX DRAWINGS HEAVY DOWN AND HORIZONTAL'],
  [0x253b, 'BOX DRAWINGS HEAVY UP AND HORIZONTAL'],
  [0x254b, 'BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL'],
  [0x2588, 'FULL BLOCK'],
  [0x2591, 'LIGHT SHADE'],
  [0x2592, 'MEDIUM SHADE'],
  [0x2593, 'DARK SHADE'],
  [0x25a0, 'BLACK SQUARE'],
  [0x25a1, 'WHITE SQUARE'],
  [0x25b2, 'BLACK UP-POINTING TRIANGLE'],
  [0x25b6, 'BLACK RIGHT-POINTING TRIANGLE'],
  [0x25bc, 'BLACK DOWN-POINTING TRIANGLE'],
  [0x25c0, 'BLACK LEFT-POINTING TRIANGLE'],
  [0x25cb, 'WHITE CIRCLE'],
  [0x25cc, 'DOTTED CIRCLE'],
  [0x25cf, 'BLACK CIRCLE'],
  [0x2600, 'BLACK SUN WITH RAYS'],
  [0x2601, 'CLOUD'],
  [0x2602, 'UMBRELLA'],
  [0x2603, 'SNOWMAN'],
  [0x2605, 'BLACK STAR'],
  [0x2606, 'WHITE STAR'],
  [0x2610, 'BALLOT BOX'],
  [0x2611, 'BALLOT BOX WITH CHECK'],
  [0x2612, 'BALLOT BOX WITH X'],
  [0x263a, 'WHITE SMILING FACE'],
  [0x2640, 'FEMALE SIGN'],
  [0x2642, 'MALE SIGN'],
  [0x2660, 'BLACK SPADE SUIT'],
  [0x2663, 'BLACK CLUB SUIT'],
  [0x2665, 'BLACK HEART SUIT'],
  [0x2666, 'BLACK DIAMOND SUIT'],
  [0x2695, 'STAFF OF AESCULAPIUS'],
  [0x26a0, 'WARNING SIGN'],
  [0x26a1, 'HIGH VOLTAGE SIGN'],
  [0x2705, 'WHITE HEAVY CHECK MARK'],
  [0x2708, 'AIRPLANE'],
  [0x2713, 'CHECK MARK'],
  [0x2714, 'HEAVY CHECK MARK'],
  [0x2715, 'MULTIPLICATION X'],
  [0x2716, 'HEAVY MULTIPLICATION X'],
  [0x2717, 'BALLOT X'],
  [0x2728, 'SPARKLES'],
  [0x274c, 'CROSS MARK'],
  [0x2764, 'HEAVY BLACK HEART'],
  [0x2b1b, 'BLACK LARGE SQUARE'],
  [0x2b1c, 'WHITE LARGE SQUARE'],
  [0x2b50, 'WHITE MEDIUM STAR'],
  [0x3000, 'IDEOGRAPHIC SPACE'],
  [0x3001, 'IDEOGRAPHIC COMMA'],
  [0x3002, 'IDEOGRAPHIC FULL STOP'],
  [0x3164, 'HANGUL FILLER'],
  [0xfeff, 'ZERO WIDTH NO-BREAK SPACE'],
  [0xffa0, 'HALFWIDTH HANGUL FILLER'],
  [0xfffc, 'OBJECT REPLACEMENT CHARACTER'],
  [0xfffd, 'REPLACEMENT CHARACTER'],
  [0x1f308, 'RAINBOW'],
  [0x1f30d, 'EARTH GLOBE EUROPE-AFRICA'],
  [0x1f31f, 'GLOWING STAR'],
  [0x1f373, 'COOKING'],
  [0x1f389, 'PARTY POPPER'],
  [0x1f3f3, 'WAVING WHITE FLAG'],
  [0x1f3f4, 'WAVING BLACK FLAG'],
  [0x1f431, 'CAT FACE'],
  [0x1f436, 'DOG FACE'],
  [0x1f440, 'EYES'],
  [0x1f44b, 'WAVING HAND SIGN'],
  [0x1f44c, 'OK HAND SIGN'],
  [0x1f44d, 'THUMBS UP SIGN'],
  [0x1f44f, 'CLAPPING HANDS SIGN'],
  [0x1f466, 'BOY'],
  [0x1f467, 'GIRL'],
  [0x1f468, 'MAN'],
  [0x1f469, 'WOMAN'],
  [0x1f494, 'BROKEN HEART'],
  [0x1f496, 'SPARKLING HEART'],
  [0x1f499, 'BLUE HEART'],
  [0x1f49a, 'GREEN HEART'],
  [0x1f49c, 'PURPLE HEART'],
  [0x1f4a9, 'PILE OF POO'],
  [0x1f4af, 'HUNDRED POINTS SYMBOL'],
  [0x1f4bb, 'PERSONAL COMPUTER'],
  [0x1f4bc, 'BRIEFCASE'],
  [0x1f525, 'FIRE'],
  [0x1f52c, 'MICROSCOPE'],
  [0x1f5a4, 'BLACK HEART'],
  [0x1f600, 'GRINNING FACE'],
  [0x1f602, 'FACE WITH TEARS OF JOY'],
  [0x1f60a, 'SMILING FACE WITH SMILING EYES'],
  [0x1f60d, 'SMILING FACE WITH HEART-SHAPED EYES'],
  [0x1f642, 'SLIGHTLY SMILING FACE'],
  [0x1f64f, 'PERSON WITH FOLDED HANDS'],
  [0x1f680, 'ROCKET'],
  [0x1f90d, 'WHITE HEART'],
  [0x1f914, 'THINKING FACE'],
  [0x1f923, 'ROLLING ON THE FLOOR LAUGHING'],
  [0x1f970, 'SMILING FACE WITH SMILING EYES AND THREE HEARTS'],
  [0x1f9d1, 'ADULT'],
  [0x1f9e1, 'ORANGE HEART'],
];

const TABLE = new Map<number, string>([
  ...seq(0x00, C0),
  ...seq(0x20, ASCII_PUNCT),
  ...seq(0xa0, LATIN1),
  ...seq(0x2000, GENERAL_PUNCTUATION),
  ...seq(0x20a0, CURRENCY),
  ...seq(0x2190, ARROWS),
  ...seq(0x2200, MATH),
  ...seq(0x2500, BOX_DRAWING, 'BOX DRAWINGS '),
  ...seq(0x2550, BOX_DOUBLE, 'BOX DRAWINGS '),
  ...seq(0x391, GREEK_LETTERS.replace('FINAL SIGMA|', '|'), 'GREEK CAPITAL LETTER '),
  ...seq(0x3b1, GREEK_LETTERS, 'GREEK SMALL LETTER '),
  ...seq(0x400, CYRILLIC_EXTRA, 'CYRILLIC CAPITAL LETTER '),
  ...seq(0x410, CYRILLIC_BASIC, 'CYRILLIC CAPITAL LETTER '),
  ...seq(0x430, CYRILLIC_BASIC, 'CYRILLIC SMALL LETTER '),
  ...seq(0x450, CYRILLIC_EXTRA, 'CYRILLIC SMALL LETTER '),
  ...SINGLES,
]);

/** Combining marks as they appear in precomposed letter names ("… WITH ACUTE"). */
const MARK_IN_NAME: Record<number, string> = {
  0x300: 'GRAVE',
  0x301: 'ACUTE',
  0x302: 'CIRCUMFLEX',
  0x303: 'TILDE',
  0x304: 'MACRON',
  0x306: 'BREVE',
  0x307: 'DOT ABOVE',
  0x308: 'DIAERESIS',
  0x309: 'HOOK ABOVE',
  0x30a: 'RING ABOVE',
  0x30b: 'DOUBLE ACUTE',
  0x30c: 'CARON',
  0x30f: 'DOUBLE GRAVE',
  0x311: 'INVERTED BREVE',
  0x31b: 'HORN',
  0x323: 'DOT BELOW',
  0x324: 'DIAERESIS BELOW',
  0x325: 'RING BELOW',
  0x326: 'COMMA BELOW',
  0x327: 'CEDILLA',
  0x328: 'OGONEK',
  0x32d: 'CIRCUMFLEX BELOW',
  0x32e: 'BREVE BELOW',
  0x330: 'TILDE BELOW',
  0x331: 'LINE BELOW',
};

const COMBINING =
  'GRAVE ACCENT|ACUTE ACCENT|CIRCUMFLEX ACCENT|TILDE|MACRON|OVERLINE|BREVE|DOT ABOVE|DIAERESIS|HOOK ABOVE|RING ABOVE|DOUBLE ACUTE ACCENT|CARON|VERTICAL LINE ABOVE|DOUBLE VERTICAL LINE ABOVE|DOUBLE GRAVE ACCENT|' +
  'CANDRABINDU|INVERTED BREVE|TURNED COMMA ABOVE|COMMA ABOVE|REVERSED COMMA ABOVE|COMMA ABOVE RIGHT|GRAVE ACCENT BELOW|ACUTE ACCENT BELOW|LEFT TACK BELOW|RIGHT TACK BELOW|LEFT ANGLE ABOVE|HORN|LEFT HALF RING BELOW|UP TACK BELOW|DOWN TACK BELOW|PLUS SIGN BELOW|' +
  'MINUS SIGN BELOW|PALATALIZED HOOK BELOW|RETROFLEX HOOK BELOW|DOT BELOW|DIAERESIS BELOW|RING BELOW|COMMA BELOW|CEDILLA|OGONEK|VERTICAL LINE BELOW|BRIDGE BELOW|INVERTED DOUBLE ARCH BELOW|CARON BELOW|CIRCUMFLEX ACCENT BELOW|BREVE BELOW|INVERTED BREVE BELOW|' +
  'TILDE BELOW|MACRON BELOW|LOW LINE|DOUBLE LOW LINE|TILDE OVERLAY|SHORT STROKE OVERLAY|LONG STROKE OVERLAY|SHORT SOLIDUS OVERLAY|LONG SOLIDUS OVERLAY';
for (const [cp, n] of seq(0x300, COMBINING, 'COMBINING ')) TABLE.set(cp, n);

const HANGUL_L = 'G GG N D DD R M B BB S SS _ J JJ C K T P H'.split(' ').map((s) => (s === '_' ? '' : s));
const HANGUL_V = 'A AE YA YAE EO E YEO YE O WA WAE OE YO U WEO WE WI YU EU YI I'.split(' ');
const HANGUL_T = '_ G GG GS N NJ NH D L LG LM LB LS LT LP LH M B BS S SS NG J C K T P H'.split(' ').map((s) => (s === '_' ? '' : s));

const FITZPATRICK = ['1-2', '3', '4', '5', '6'];
const UNIFIED_IDEOGRAPH = /^\p{Unified_Ideograph}$/u;

const hex = (cp: number) => cp.toString(16).toUpperCase().padStart(4, '0');

function isLatinLetterBlock(cp: number) {
  return (cp >= 0xc0 && cp <= 0x24f) || (cp >= 0x1e00 && cp <= 0x1eff);
}

/** The character's Unicode name if this table knows it, else null. */
export function charName(cp: number): string | null {
  const direct = TABLE.get(cp);
  if (direct) return direct;
  if (cp >= 0x41 && cp <= 0x5a) return `LATIN CAPITAL LETTER ${String.fromCharCode(cp)}`;
  if (cp >= 0x61 && cp <= 0x7a) return `LATIN SMALL LETTER ${String.fromCharCode(cp - 32)}`;
  if (cp >= 0x80 && cp <= 0x9f) return '<control>';
  if (cp >= 0xfe00 && cp <= 0xfe0f) return `VARIATION SELECTOR-${cp - 0xfe00 + 1}`;
  if (cp >= 0xe0100 && cp <= 0xe01ef) return `VARIATION SELECTOR-${cp - 0xe0100 + 17}`;
  if (cp === 0xe0001) return 'LANGUAGE TAG';
  if (cp === 0xe007f) return 'CANCEL TAG';
  if (cp >= 0xe0020 && cp <= 0xe007e) return `TAG ${charName(cp - 0xe0000)}`;
  if (cp >= 0x1f3fb && cp <= 0x1f3ff) return `EMOJI MODIFIER FITZPATRICK TYPE-${FITZPATRICK[cp - 0x1f3fb]}`;
  if (cp >= 0x1f1e6 && cp <= 0x1f1ff) return `REGIONAL INDICATOR SYMBOL LETTER ${String.fromCharCode(0x41 + cp - 0x1f1e6)}`;
  if (cp >= 0xff01 && cp <= 0xff5e) return `FULLWIDTH ${charName(cp - 0xfee0)}`;
  if (cp >= 0xac00 && cp <= 0xd7a3) {
    const s = cp - 0xac00;
    return `HANGUL SYLLABLE ${HANGUL_L[Math.floor(s / 588)]}${HANGUL_V[Math.floor((s % 588) / 28)]}${HANGUL_T[s % 28]}`;
  }
  const ch = String.fromCodePoint(cp);
  if (UNIFIED_IDEOGRAPH.test(ch)) return `CJK UNIFIED IDEOGRAPH-${hex(cp)}`;
  // Accented Latin letters: base letter + exactly one combining mark.
  if (isLatinLetterBlock(cp) && ch.normalize('NFC') === ch) {
    const parts = [...ch.normalize('NFD')].map((c) => c.codePointAt(0)!);
    if (parts.length === 2 && MARK_IN_NAME[parts[1]]) {
      const base = charName(parts[0]);
      if (base && /^LATIN (CAPITAL|SMALL) LETTER /.test(base) && !base.includes(' WITH ')) return `${base} WITH ${MARK_IN_NAME[parts[1]]}`;
    }
  }
  return null;
}

/** Short labels for invisible characters, shown in place of the (blank) glyph. */
export const INVISIBLE_LABELS: Record<number, string> = {
  0x00a0: 'NBSP',
  0x00ad: 'SHY',
  0x034f: 'CGJ',
  0x061c: 'ALM',
  0x115f: 'HCF',
  0x1160: 'HJF',
  0x1680: 'OSM',
  0x180e: 'MVS',
  0x2000: 'NQSP',
  0x2001: 'MQSP',
  0x2002: 'ENSP',
  0x2003: 'EMSP',
  0x2004: '3/MSP',
  0x2005: '4/MSP',
  0x2006: '6/MSP',
  0x2007: 'FSP',
  0x2008: 'PSP',
  0x2009: 'THSP',
  0x200a: 'HSP',
  0x200b: 'ZWSP',
  0x200c: 'ZWNJ',
  0x200d: 'ZWJ',
  0x200e: 'LRM',
  0x200f: 'RLM',
  0x2028: 'LSEP',
  0x2029: 'PSEP',
  0x202a: 'LRE',
  0x202b: 'RLE',
  0x202c: 'PDF',
  0x202d: 'LRO',
  0x202e: 'RLO',
  0x202f: 'NNBSP',
  0x205f: 'MMSP',
  0x2060: 'WJ',
  0x2061: 'FA',
  0x2062: 'IT',
  0x2063: 'IS',
  0x2064: 'IP',
  0x2066: 'LRI',
  0x2067: 'RLI',
  0x2068: 'FSI',
  0x2069: 'PDI',
  0x3000: 'IDSP',
  0x3164: 'HF',
  0xfeff: 'BOM',
  0xffa0: 'HWHF',
};
